const ALERTS = [
  { type: "danger",  icon: "🚨", title: "VitaPlus Health — ROAS dropped below 2x",       desc: "ROAS fell from 3.1x to 1.9x in 7 days. Likely caused by increased competitor bids on branded keywords.", time: "2 hours ago" },
  { type: "warn",    icon: "⚠️", title: "Kiran Foods — Budget 92% spent, 8 days left",   desc: "At current burn rate, budget will exhaust by April 9th. Consider pausing low-performing ad sets.", time: "4 hours ago" },
  { type: "warn",    icon: "⚠️", title: "Google Ads account — Overpacing by 12%",        desc: "Total Google Ads spend is tracking 12% above plan for April. Review bids across all client accounts.", time: "Yesterday" },
  { type: "info",    icon: "📊", title: "NexGen Tech — CTR increased by 34%",            desc: "New ad creative 'B' is outperforming control by 34% CTR. Consider scaling budget to this ad set.", time: "Yesterday" },
  { type: "success", icon: "🎉", title: "Zara Apparel — Best ROAS month ever (6.2x)",    desc: "April is tracking as Zara's best performing month. Revenue attribution up ₹12L vs March.", time: "2 days ago" },
  { type: "info",    icon: "🔍", title: "New keyword opportunity — 'affordable CRM India'", desc: "High-intent keyword with low competition detected in NexGen Tech's Search Query Report.", time: "3 days ago" },
  { type: "warn",    icon: "⚠️", title: "SkyBuild Infra — Campaigns paused",             desc: "All campaigns paused at client request. Monthly report still scheduled for May 1st.", time: "4 days ago" },
  { type: "success", icon: "✅", title: "Monthly reports sent to 6 clients",             desc: "March performance reports successfully generated and sent. All 6 clients notified by email.", time: "Apr 1st" },
];

const colorMap = {
  danger:  "alert-danger",
  warn:    "alert-warn",
  info:    "alert-info",
  success: "alert-success",
};

export default function Alerts() {
  return (
    <div>
      <div className="page-header">
        <h1>Alerts & Insights</h1>
        <p>Real-time anomalies and opportunities detected across all client accounts</p>
      </div>

      {/* Summary */}
      <div className="metric-grid" style={{ gridTemplateColumns: "repeat(4, minmax(0,1fr))", marginBottom: 24 }}>
        {[
          { label: "Critical Alerts",  value: "1",  change: "Needs action now", up: false },
          { label: "Warnings",         value: "3",  change: "Review this week",  up: false },
          { label: "Opportunities",    value: "2",  change: "Act to grow ROAS",  up: true  },
          { label: "Resolved Today",   value: "2",  change: "All clear",         up: true  },
        ].map((m) => (
          <div className="metric-card" key={m.label}>
            <div className="metric-label">{m.label}</div>
            <div className="metric-value">{m.value}</div>
            <div className={`metric-change ${m.up ? "up" : "down"}`}>{m.change}</div>
          </div>
        ))}
      </div>

      {/* Alert list */}
      <div className="panel">
        <div className="panel-title">All Alerts</div>
        <div className="alert-list">
          {ALERTS.map((a, i) => (
            <div className={`alert-item ${colorMap[a.type]}`} key={i}>
              <span className="alert-icon">{a.icon}</span>
              <div className="alert-body">
                <div className="alert-title">{a.title}</div>
                <div className="alert-desc">{a.desc}</div>
              </div>
              <span className="alert-time">{a.time}</span>
            </div>
          ))}
        </div>
      </div>

      <div style={{ marginTop: 20, padding: "16px 18px", background: "#eef3ff", borderRadius: 10, fontSize: 12.5, color: "#185FA5" }}>
        🤖 <strong>Phase 4:</strong> These alerts will be auto-generated by ML — anomaly detection will fire before your clients even notice a problem.
      </div>
    </div>
  );
}